settings:
  bullet: "-"
  rule: '-'
  extentions: "micromark/micromark-extension-frontmatter"
plugins:
  # Check that markdown is consistent.
  #- remark-preset-lint-consistent
  # Few recommended rules.
  #- remark-preset-lint-recommended
  # Generate a table of contents in `## Contents`
  - - remark-toc
    - heading: contents
