settings:
  bullet: "-"
  #rule: '-'
plugins:
  # Check that markdown is consistent.
  #- remark-preset-lint-consistent
  # Few recommended rules.
  #- remark-preset-lint-recommended
  - - remark-frontmatter
    - type: 'yaml'
      marker: '-'
    - remark-parse    
  - - remark-slug    
  - - remark-autolink-headings
    - behavior: append
    - linkProperties: "{ariaHidden: 'false', tabIndex: 0}"
  - - remark-html
    - sanitize: false    
