---
settings:
  bullet: "-"
plugins:
- - remark-frontmatter
  - type: yaml
    marker: "-"
  - remark-parse
- - remark-slug
- - remark-autolink-headings
  - behavior: wrap
    linkProperties:
      ariaHidden: 'true'
      tabIndex: -1
      rel: bookmark
- - remark-html
  - sanitize: false
