{
  "settings": {
    "bullet": "-"
  },
  "plugins": [
    [
      "remark-frontmatter",
      {
        "type": "yaml",
        "marker": "-"
      },
      "remark-parse"
    ],
    [
      "remark-slug"
    ],
    [
      "remark-autolink-headings",
      {
        "behavior": "append"
      }
    ],
    [
      "remark-html",
      {
        "sanitize": false
      }
    ]
  ]
} 
