name: New content or feature suggestion
description: Proposals for new content or features on AppCode
title: Enter your proposal here
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to put together a proposal for adding/updating content or a website feature on AppCode.
        We have a well-defined process for handling these requests.
  - type: textarea
    attributes:
      label: Proposal
      description: Please describe the content or feature you are proposing and why it is needed.
    validations:
      required: true
  - type: textarea
    id: task-list
    attributes:
      label: Task list
      description: List the steps involved to complete this project.
      value: |
        - [ ] 
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Please add any additional information to support this proposal (screenshots, specification links, browser implementation bugs etc...)
  - type: input
    attributes:
      label: Are you willing to support this work?
      description: AppCode is an open source project and welcomes contributions. Please state whether you are willing to help with the proposed work and in what capacity; this can be undertaking the work or supporting with reviews and/or queries.
  - type: textarea
    attributes:
      label: Depends on
      description: |
        Does this work depend on any other work to be complete before it can begin? (Please provide links to existing issues if possible).
