on:
  push:
    branches:
      - master
name: Remark
jobs:
  generateNewMarkdown:
    name: Remark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run remark cli
        uses: tj-actions/remark@v3
        with:
          plugins: |
             remark-toc
             remark-frontmatter
             remark-prism
             remark-slug
          files: |
             *.md
          rc_path: .remarkrc-master.yml   
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
             *.md         
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          base: "master"
          title: "Remark Format Markdown"
          branch: "chore/update-markdown"
          commit-message: "Updated markdown content"
          body: "Updated markdown content format as set in .remarkrc.yml"
          token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Run remark cli convert markdown to HTML
        if: steps.verify-changed-files.outputs.files_changed == 'false'
        uses: tj-actions/remark@v3
        with:
          plugins: |
             remark-toc
             remark-frontmatter
             remark-prism
             remark-parse
             rehype-slug
             remark-autolink-headings
             remark-html
          files: |
             *.md
          rc_path: .remarkrc.js         
      - name: Commit Converted HTML to Rendered Branch
        if: steps.verify-changed-files.outputs.files_changed == 'false'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Markdown to HTML Conversion
          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: rendered     
          file_pattern: '*.html'
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
          skip_checkout: true
          push_options: '--force'
          
      
