on:
  push:
    branches:
      - master
name: Remark
jobs:
  generateNewMarkdown:
    name: Remark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run remark cli
        uses: tj-actions/remark@v3
        with:
          plugins: |
             remark-toc
             remark-frontmatter
             remark-prism
             remark-slug
          files: |
             *.md
          rc_path: .remarkrc-master.yml   
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
             *.md         
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          base: "master"
          title: "Remark Format Markdown"
          branch: "chore/update-markdown"
          commit-message: "Updated markdown content"
          body: "Updated markdown content format as set in .remarkrc.yml"
          token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Run remark cli convert markdown to HTML
        if: steps.verify-changed-files.outputs.files_changed == 'false'
        uses: tj-actions/remark@v3
        with:
          plugins: |
             remark-toc
             remark-frontmatter
             remark-prism
             remark-parse
             rehype-slug
             remark-autolink-headings
             remark-html
          files: |
             *.md
          rc_path: .remarkrc-rendered.yml        
      - name: Commit Converted HTML to Rendered Branch
        if: steps.verify-changed-files.outputs.files_changed == 'false'
 #       uses: stefanzweifel/git-auto-commit-action@v4
 #       with:
 #         # Optional. Commit message for the created commit.
 #         # Defaults to "Apply automatic changes"
 #         commit_message: Automated Markdown to HTML Conversion
 #         # Optional. Local and remote branch name where commit is going to be pushed
 #         #  to. Defaults to the current branch.
 #         #  You might need to set `create_branch: true` if the branch does not exist.
 #         branch: rendered     
 #         file_pattern: '*.html'
 #         # Optional. Disable dirty check and always try to create a commit and push
 #         skip_dirty_check: true
 #         skip_checkout: true
 #         push_options: '--force'
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          #add: 'src'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Remark Bot

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          #author_email: mail@example.com

          # Additional arguments for the git commit command. The --message argument is already set by the message input.
          # Default: ''
          #commit: --signoff

          # The name of the custom committer you want to use, if different from the author of the commit.
          # Default: the name of the author (set with either author_name or default_author)
          committer_name: Remark Bot

          # The email of the custom committer you want to use, if different from the author of the commit.
          # Default: the email of the author (set with either author_email or default_author)
          #committer_email: mail@example.com

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
          # Default: '.'
          #cwd: './path/to/the/repo'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          #default_author: github_actor

          # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
          # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ. 
          # Default: --tags --force
          #fetch: false

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Automated Markdown to HTML Conversion'

          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
          new_branch: rendered

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          #pathspec_error_handling: ignore

          # Arguments for the git pull command. By default, the action does not pull.
          # Default: ''
          #pull: '--rebase --autostash ...'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: '--force'

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          remove: '*.md'

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          #tag: 'v1.0.0 --force'

          # Arguments for the git push --tags command (any additional argument will be added after --tags)
          # Default: ''
          #tag_push: '--force' 
      
